### ISSUE TITLE
What is `art`?

### ISSUE THREAD

**Issue by LightspeedLife** [gawlk/lamp#2]
This program looks really cool! I'd love to integrate it into my rice, but I have no idea what `art` is. It doesn't seem to be in my distro's repositories--Arch community, extra, nor in AUR--Could you provide a link to the project's homepage or how you came about aquiring `art`?

**Comment by NerdyPepper** [comment]
https://github.com/gawlk/art

**Comment by LightspeedLife** [comment]
ah--I see I'm being a goof. Thanks!
